inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4
Lint/AssignmentInCondition:
  Enabled: false
Metrics/LineLength:
  Enabled: false
  Max: 100
Rails:
  Enabled: true
Style/AsciiComments:
  Enabled: false
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/ClassAndModuleChildren:
  Enabled: false
Style/CollectionMethods:
  Description: Preferred collection methods.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#map-find-select-reduce-size
  Enabled: true
  PreferredMethods:
    collect: map
    collect!: map!
    find: detect
    find_all: select
    reduce: inject
Style/Documentation:
  Enabled: false
Style/FileName:
  Description: Use snake_case for source file names.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#snake-case-files
  Enabled: false
  Exclude: []
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'
