default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["postgres_pool"] %>
  username: <%= ENV["postgres_username"] %>
  password: <%= ENV["postgres_password_plain"] %>
  host: <%= ENV["postgres_host"] %>

development:
  <<: *default
  database: gambala_development

test:
  <<: *default
  database: gambala_test

production:
  <<: *default
  database: gambala_production
